# Generated by Django 4.1.7 on 2023-03-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('amfi_nav_download_dropdown_code', models.IntegerField(blank=True, null=True, unique=True)),
                ('amc_assets_under_management', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('is_being_sold', models.BooleanField(default=True)),
                ('f_amc_code', models.CharField(blank=True, max_length=3, null=True)),
                ('amc_logo', models.CharField(max_length=100)),
                ('amc_website_url', models.CharField(blank=True, max_length=200, null=True)),
                ('scheme_information_document_url', models.CharField(blank=True, max_length=200, null=True)),
                ('nominee_url', models.CharField(blank=True, max_length=200, null=True)),
                ('expense_ratio_url', models.CharField(blank=True, max_length=200, null=True)),
                ('expense_ratio_url_remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('last_nav_pull_date_from_amfi', models.DateField(blank=True, null=True)),
                ('rta_amc_code', models.CharField(blank=True, max_length=64, null=True)),
                ('is_isip_available', models.BooleanField(default=True)),
                ('cio', models.CharField(blank=True, max_length=150, null=True)),
                ('ceo', models.CharField(blank=True, max_length=150, null=True)),
                ('management_trustee', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_type', models.CharField(blank=True, max_length=50, null=True)),
                ('address1', models.CharField(blank=True, max_length=200, null=True)),
                ('address2', models.CharField(blank=True, max_length=200, null=True)),
                ('address3', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('pin', models.IntegerField(blank=True, null=True)),
                ('amc_aum_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kbapp_amc',
            },
        ),
    ]
