# Generated by Django 4.1.7 on 2023-03-10 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbapp', '0002_amcfund_amcfundscheme_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='amcfund',
            name='AMCFund_amc_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='amcfund',
            name='AMCFund_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='amcfund',
            name='AMCFund_is_being_sold_idx',
        ),
        migrations.RemoveIndex(
            model_name='amcfund',
            name='AMCFund_fund_class_idx',
        ),
        migrations.RemoveIndex(
            model_name='amcfund',
            name='AMCFund_fund_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='amcfund',
            name='AMCFund_fund_sub_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='amcfund',
            name='AMCFund_fund_type_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='amcfund',
            name='AMCFund_fund_category_idx',
        ),
        migrations.RemoveIndex(
            model_name='amcfund',
            name='AMCFund_rta_fund_code_idx',
        ),
        migrations.AlterUniqueTogether(
            name='amcfund',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='amcfund',
            name='AMC',
        ),
    ]
