# Generated by Django 4.1.7 on 2023-02-23 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_id', models.CharField(max_length=30)),
                ('bank_name', models.CharField(max_length=30)),
                ('bank_website', models.URLField()),
                ('bank_number', models.CharField(max_length=30)),
                ('bank_logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=50)),
                ('cheque_image', models.ImageField(upload_to='')),
                ('branch_name', models.CharField(max_length=30)),
                ('is_cheque_verified', models.BooleanField()),
                ('name_as_per_bank_record', models.CharField(max_length=30)),
                ('verification_mode', models.CharField(max_length=30)),
                ('verification_status', models.BooleanField()),
                ('account_type', models.CharField(max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bank')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
